version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_NAME=employee_db
      - DB_USER=dassault_admin
      - DB_PASSWORD=pwd
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: dassault_admin
      MYSQL_PASSWORD: pwd
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
